/*
 * HC-SR04_sensor.h
 *
 *  Created on: OCT 13, 2022
 *      Author: Mina Sobhy
 *      description: header file for the ultrasonic sensor driver
 *
 */

#ifndef HC_SR04_SENSOR_H_
#define HC_SR04_SENSOR_H_

#include "std_types.h"


/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
/* ultrasonic sensor trigger pin */
#define TRIGGER_PORT	PORTC_ID
#define TRIGGER_PIN		PIN0_ID


/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description:
 * 1. Initialize the ICU driver as required.
 * 2. Setup the ICU call back function.
 * 3. Setup the direction for the trigger pin as output pin through the
 *    GPIO driver.
 */
void Ultrasonic_init(void);

/*
 * Description:
 * 1. Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void);

/*
 * Description:
 * 1. Send the trigger pulse by using Ultrasonic_Trigger function.
 * 2. Start the measurements by the ICU from this moment.
 * 3. return the measured distance in Centimeter.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * Description:
 * 1. This is the call back function called by the ICU driver.
 * 2. This is used to calculate the high time (pulse time) generated by
 *    the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);

#endif /* HC_SR04_SENSOR_H_ */
